### ISSUE TITLE
[Docs] README 업데이트

### ISSUE THREAD

**Issue by funnysunny08** [Runnect/Runnect-Server#81]
### 😶 무슨 이슈인가요?

---
리드미 최종과제 업데이트

### 🤔 어떻게 해결할 예정인가요?

---

- [x] 서비스 핵심 기능 소개 (이미지 포함)
- [x] dependencies module ( package.json )
- [x] server architecture

### 🤯 주의할 점이 있나요?

---

**Comment by dlwogus0128** [comment]
들렀다갑니다..
